// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDv7OgFSw27obkt2q6cOvF10-R6VjDLXK8',
    appId: '1:140210503368:web:c1ffc36c60bc1f988b2ffd',
    messagingSenderId: '140210503368',
    projectId: 'alumning-5bea2',
    authDomain: 'alumning-5bea2.firebaseapp.com',
    storageBucket: 'alumning-5bea2.appspot.com',
    measurementId: 'G-6PM42PE531',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnEmw6jUWa-66A1dCALEbmu4GO0nfLvSU',
    appId: '1:140210503368:android:d0af81d1bfcbb12a8b2ffd',
    messagingSenderId: '140210503368',
    projectId: 'alumning-5bea2',
    storageBucket: 'alumning-5bea2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT_TQT9AVeOf_BCWAqXxKpbS8MVOMWyLI',
    appId: '1:140210503368:ios:33bafc56b6050b988b2ffd',
    messagingSenderId: '140210503368',
    projectId: 'alumning-5bea2',
    storageBucket: 'alumning-5bea2.appspot.com',
    iosBundleId: 'com.example.ngAlumni',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAT_TQT9AVeOf_BCWAqXxKpbS8MVOMWyLI',
    appId: '1:140210503368:ios:33bafc56b6050b988b2ffd',
    messagingSenderId: '140210503368',
    projectId: 'alumning-5bea2',
    storageBucket: 'alumning-5bea2.appspot.com',
    iosBundleId: 'com.example.ngAlumni',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDv7OgFSw27obkt2q6cOvF10-R6VjDLXK8',
    appId: '1:140210503368:web:9e2a45a262445e4a8b2ffd',
    messagingSenderId: '140210503368',
    projectId: 'alumning-5bea2',
    authDomain: 'alumning-5bea2.firebaseapp.com',
    storageBucket: 'alumning-5bea2.appspot.com',
    measurementId: 'G-CY3WBLS1P3',
  );
}
